### ISSUE TITLE
BusKill.__init__ incompatible with pytest's log handler (_LiveLoggingNullHandler has no baseFilename)

### ISSUE THREAD

**Issue by prashanth-kaki** [BusKill/buskill-app#131]
**Describe the bug**
BusKill.__init__ crashes when instantiated under pytest. On line 227:

    self.LOG_FILE_PATH = logger.root.handlers[0].baseFilename

pytest replaces the root log handler with _LiveLoggingNullHandler which 
has no baseFilename attribute, causing AttributeError on every test.

**To Reproduce**
1. pip install pytest
2. Write any test that instantiates BusKill()
3. Run pytest
4. AttributeError: '_LiveLoggingNullHandler' object has no attribute 'baseFilename'

**Expected behavior**
BusKill should be safely instantiable in any logging environment.

**Suggested fix**
Change line 227 in buskill/__init__.py from:
    self.LOG_FILE_PATH = logger.root.handlers[0].baseFilename
To:
    handler = logger.root.handlers[0]
    self.LOG_FILE_PATH = getattr(handler, 'baseFilename', None)

**Context**
Discovered while adding the first unit test suite (PR #XX — replace with your PR **number).******

**Comment by maltfield** [comment]
Hi, thanks for the report :)

Can you lease provide Steps To Reproduce, which we can just copy and paste on a Debian 12 or Debian 13 system to get the crash?

**Comment by prashanth-kaki** [comment]
Hi, thanks for looking into it.

Here are the steps to reproduce on Debian 12 or Debian 13:

```bash
git clone https://github.com/BusKill/buskill-app.git
cd buskill-app
pip install pytest
pytest tests/test_buskill.py -v
```

The crash occurs on `BusKill.__init__` line 227:

```python
self.LOG_FILE_PATH = logger.root.handlers[0].baseFilename
```

When pytest runs, it replaces `logging.root.handlers[0]` with its own `_LiveLoggingNullHandler` which has no `baseFilename` attribute, causing `AttributeError` on every test that instantiates `BusKill()`.

The fix is:

```python
handler = logger.root.handlers[0]
self.LOG_FILE_PATH = getattr(handler, 'baseFilename', None)
```

**Comment by maltfield** [comment]
@Raihan93-coder are you able to reproduce this and interested in pushing a fix?

**Comment by Raihan93-coder** [comment]
I was able to reproduce the issue on Parrot Security 6.4 (lorikeet), which is based on Debian 12.

The error still occurs after the change introduced in PR #121. That PR modified:

`self.LOG_FILE_PATH = logger.root.handlers[0].baseFilename`

to:

`self.LOG_FILE_PATH = logger.root.handlers[0].baseFilename if logger.root.handlers else None`

The intention of that change was different from this issue. In PR #121, the BusKill class could be instantiated before logging was fully configured, which could lead to an IndexError when logger.root.handlers was empty. The added check was intended to prevent that specific failure mode.

However, after reproducing this issue, it appears that pytest introduces a different failure mode. Under pytest, logger.root.handlers[0] becomes a _LiveLoggingNullHandler, which does not provide a baseFilename attribute. As a result, the code still raises:

AttributeError: '_LiveLoggingNullHandler' object has no attribute 'baseFilename'

So while the PR #121 change protects against an empty handler list, it does not protect against handlers that do not expose a baseFilename attribute.

I think the proposed fix using getattr() addresses the pytest issue:

> handler = logger.root.handlers[0]
> self.LOG_FILE_PATH = getattr(handler, 'baseFilename', None)

Although I would suggest combining both checks so that we handle both failure modes:

> handler = logger.root.handlers[0] if logger.root.handlers else None
> self.LOG_FILE_PATH = getattr(handler, "baseFilename", None) if handler else None

This would prevent:

- IndexError when no handlers exist.
- AttributeError when a handler exists but does not provide baseFilename (such as pytest's _LiveLoggingNullHandler).

@prashanth-kaki does this match what you observed during your testing?

**Comment by prashanth-kaki** [comment]
Yes, this matches exactly what I observed. Under pytest, logger.root.handlers[0] is a _LiveLoggingNullHandler which has no baseFilename attribute, causing the AttributeError.
Your combined fix is better than my original suggestion since it handles both failure modes:

```python
handler = logger.root.handlers[0] if logger.root.handlers else None
self.LOG_FILE_PATH = getattr(handler, "baseFilename", None) if handler else None
```
This is cleaner and more defensive. Thanks for verifying and improving on it.
